### ISSUE TITLE
CasC issue with gitLabConnectionConfig : empty connection created

### ISSUE THREAD

**Issue by touzoun** [jenkinsci/gitlab-plugin#1643]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

GitLab Plugin Version 1.8.0 

### Reproduction steps

When applying this casc : 

```
      gitLabConnectionConfig:
        connections:
        - apiTokenId: {{ .Values.envVars.gitlabId | quote }}
          clientBuilderId: "autodetect"
          connectionTimeout: 10
          ignoreCertificateErrors: false
          name: "gitlab"
          readTimeout: 10
          url: {{ printf "http://%s" .Values.global.principalScmHost | quote }}
        useAuthenticatedEndpoint: true
```

an empty connection appears in the configuration .
When exporting the conf-as-code, I can see an added bloc causing the empty connection : 

```
  gitLabConnectionConfig:
    connections:
    - apiTokenId: "xxx"
      clientBuilderId: "autodetect"
      connectionTimeout: 10
      ignoreCertificateErrors: false
      name: "gitlab"
      readTimeout: 10
      url: "http://xxxx"
    - clientBuilderId: "autodetect"
      connectionTimeout: 10
      ignoreCertificateErrors: false
      readTimeout: 10
    useAuthenticatedEndpoint: true
```

### Expected Results

i don't want this added : 

```
    - clientBuilderId: "autodetect"
      connectionTimeout: 10
      ignoreCertificateErrors: false
      readTimeout: 10
    useAuthenticatedEndpoint: true
```

### Actual Results

```
  gitLabConnectionConfig:
    connections:
    - apiTokenId: "xxx"
      clientBuilderId: "autodetect"
      connectionTimeout: 10
      ignoreCertificateErrors: false
      name: "gitlab"
      readTimeout: 10
      url: "http://xxxx"
    - clientBuilderId: "autodetect"
      connectionTimeout: 10
      ignoreCertificateErrors: false
      readTimeout: 10
    useAuthenticatedEndpoint: true
```
